inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Layout/EmptyLineBetweenDefs:
  Enabled: true
  AllowAdjacentOneLineDefs: true


Layout/ParameterAlignment:
  Enabled: true
  EnforcedStyle: with_first_parameter

Layout/SpaceInsideParens:
  Enabled: true

Layout/FirstArrayElementIndentation:
  Enabled: true
Layout/FirstHashElementIndentation:
  Enabled: true

Layout/BlockAlignment:
  Enabled: true