default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: uchi_internship_development

test:
  <<: *default
  database: uchi_internship_test

production:
  <<: *default
  database: uchi_internship_production
  username: uchi_internship
  password: <%= ENV["UCHI_INTERNSHIP_DATABASE_PASSWORD"] %>
